server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**

            - id: employee-service
              uri: http://localhost:8082
              predicates:
                - Path=/employees/**

            - id: leave-service
              uri: http://localhost:8083
              predicates:
                - Path=/leave/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE